### ISSUE TITLE
Broken zsh completion menu

### ISSUE THREAD

**Issue by anuvyklack** [jeffreytse/zsh-vi-mode#122]
## General information

- Operating system: Pop!_OS 21.04
- ZSH framework: none
- ZSH version: 5.8-6
- ZVM version: 82f00eaefc95165f4524e77312db0d216a64a7ad

## Basic examination

- [x] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [x] I have the latest version of zsh-vi-mode
- [x] I have tested with another terminal program: kitty, gnome-terminal, tilix

## Problem description

  On the latest commit (82f00eaefc95165f4524e77312db0d216a64a7ad) zsh completion menu broke inside tmux. Outside of tmux it works.

## Reproduction steps

1. `setopt menu_complete`
2. enter tmux, print any command (`cd` for example) and press `Tab`

https://user-images.githubusercontent.com/13056013/132378718-6d132039-9cb8-44d2-9c8f-07c9c80c0f4d.mov

**Comment by jeffreytse** [comment]
Hi @anuvyklack 

Thanks for your reporting. I will work on this issue as soon as possible.

Thanks and Regards

**Comment by jeffreytse** [comment]
Hi @anuvyklack 

Could you please try this version 1549325615a5da5ec570289dfa08687cece1c5f6, and feedback me the result?

Thanks and Regards

**Comment by anuvyklack** [comment]
1549325 works fine.

**Comment by jeffreytse** [comment]
@anuvyklack Could you please provide me the information by command `echo $TERM`

**Comment by anuvyklack** [comment]
`tmux-256color`

**Comment by jeffreytse** [comment]
@anuvyklack Could you please provide me your source file (e.g. `.zshrc`) to have further check?

**Comment by StefanBoca** [comment]
@jeffreytse I also had this issue. Reverting to 1549325 fixed it, and I managed to trace it down to the following changes:
```bash
-  zvm_update_cursor
+  if [[ -n $TMUX ]]; then
+    zvm_update_cursor
+    # Fix display is not updated in the terminal of InteliJ IDE
+    zle redisplay
+  fi
```

Reverting this change fixed the issue for me.

**Comment by jeffreytse** [comment]
@StefanBoca Thanks for your reaching out, I have confirmed the reason of this issue, but I am still exploring a good way to fix this issue, at the same time, keep the compatibility of the terminal in IntelliJ IDE. Could you provide me a minimum `.zshrc` file which can reproduce this issue to have a further check? Thanks and Regards

**Comment by jeffreytse** [comment]
Hi @StefanBoca 

Thanks for your patience, now this issue has been addressed and fixed. Please update your plugin to the latest version and try again.

Thanks and Regards

**Comment by anuvyklack** [comment]
Hello, @jeffreytse.

I'm sorry, but for me still doesn't work. The same: all commits after c1480b4 are broken.

**Comment by jeffreytse** [comment]
Hi @anuvyklack 

For the temporary solution, you can comment the line [L3152](https://github.com/jeffreytse/zsh-vi-mode/blob/63e5a5209b238771e528dd22d2ac1a317ace7319/zsh-vi-mode.zsh#L3152) as below:

```zsh
 if [[ -n $TMUX ]]; then
    zvm_update_cursor
    # Fix display is not updated in the terminal of IntelliJ IDE.
    # We should update display only when the last widget isn't a
    # completion widget
    #
    # PLEASE COMMENT BELOW LINE
    #
    # [[ $LASTWIDGET =~ 'complet' ]] || zle redisplay
 fi
```

Thanks & Regards

**Comment by weirongxu** [comment]
Same problem here.
My environment:

## General information

Linux

- Operating system: Linux 5.9.16-1-MANJARO x86_64
- ZSH framework: none
- ZSH version: 5.8 (x86_64-pc-linux-gnu)
- ZVM version: 7878372
- TMUX version: 3.2a

---

MacOS

- Operating system: Darwin 20.6.0 x86_64
- ZSH framework: none
- ZSH version: 5.8.1 (x86_64-apple-darwin20.6.0)
- ZVM version: 7878372
- TMUX version: 3.2a

## Reproduction steps

1. `~/.zshrc`
    ```
    autoload -U +X compinit && compinit
    zstyle ':completion:*' menu yes select
    source /Users/raidou/repos/zsh-vi-mode/zsh-vi-mode.zsh
    ```
2. enter tmux
3. input `ls` and press tab more than twice

**Comment by michaelorr** [comment]
I am also running into this issue. My environment is structurally the same as @weirongxu 's MacOS setup

**Comment by michaelorr** [comment]
I have pushed up a PR which attempts to fix this issue:
https://github.com/jeffreytse/zsh-vi-mode/pull/191

I cannot test in IntelliJ and would love if someone were able to verify the behavior there.

**Comment by michaelorr** [comment]
Barring any further bug reports here, I think this is fixed by https://github.com/jeffreytse/zsh-vi-mode/pull/191

**Comment by michaelorr** [comment]
Thank you everyone for the helpful diagnostic information above that led to the fix and thank you to @jeffreytse for maintaining this project and merging my commit!
